build: Generate Tasks & CI Config (#437)
Co-authored-by: Tedium <tedium-markormesher[bot]@users.noreply.github.com>

diff --git a/taskfile.yml b/taskfile.yml
--- a/taskfile.yml
+++ b/taskfile.yml
@@ -8,24 +8,116 @@ includes:
 tasks:
   cachekey:
     cmds:
-      - cmd: rm -f "{{.ROOT_DIR}}/.task-meta-cachekey"*
-      - task: cachekey-js-root
-  cachekey-js:
+      - task: cachekey-root-js
+  cachekey-root:
     cmds:
-      - task: cachekey-js-root
-  cachekey-js-root:
+      - task: cachekey-root-js
+  cachekey-root-js:
     dir: '{{.ROOT_DIR}}'
+    generates:
+      - .task-meta-cache-key
     cmds:
-      - cmd: sha256sum package.json | awk '{print $1}' >> "{{.ROOT_DIR}}/.task-meta-cachekey-js"
-      - cmd: if [[ -f pnpm-lock.yaml ]]; then sha256sum pnpm-lock.yaml | awk '{print $1}' >> "{{.ROOT_DIR}}/.task-meta-cachekey-js"; fi
-      - cmd: if [[ -f yarn.lock ]]; then sha256sum yarn.lock | awk '{print $1}' >> "{{.ROOT_DIR}}/.task-meta-cachekey-js"; fi
+      - cmd: |-
+          if [ ${CI:+1} ]; then
+            PROJECT="repo"
+
+            DEPS_SHA=$(cat package.json | sha256sum | awk '{ print $1 }')
+
+            if [[ -f pnpm-lock.yaml ]]; then
+              LOCK_SHA=$(cat pnpm-lock.yaml | sha256sum | awk '{ print $1 }')
+            elif [[ -f yarn.lock ]]; then
+              LOCK_SHA=$(cat yarn.lock | sha256sum | awk '{ print $1 }')
+            else
+              LOCK_SHA="nolock"
+            fi
+
+            echo "${PROJECT}-js-v1/${DEPS_SHA}/${LOCK_SHA}" > .task-meta-cache-key
+          fi
+  cacheload:
+    cmds:
+      - task: cacheload-root-js
+  cacheload-root:
+    cmds:
+      - task: cacheload-root-js
+  cacheload-root-js:
+    dir: '{{.ROOT_DIR}}'
+    deps:
+      - cachekey-root-js
+    cmds:
+      - cmd: |-
+          if [[ -n ${CI_CACHE_TOKEN+x} ]] && [[ -f ".task-meta-cache-key" ]]; then
+            request_key=$(cat ".task-meta-cache-key" | tr -d '\r\n')
+            start_ts=$(date +%s)
+            header_file=$(mktemp)
+            cache_file=$(mktemp)
+
+            echo "loading cache..."
+            echo "request key: ${request_key}"
+            if curl -fsSL -D "${header_file}" -H "authorization: Bearer ${CI_CACHE_TOKEN}" "https://ci-cache.markormesher.co.uk/cache/${request_key}" -o "${cache_file}"; then
+              actual_key=$(cat "${header_file}" | grep -i x-cache-key | cut -d ' ' -f 2 | tr -d '\r\n')
+              size=$(du -h "${cache_file}" | awk '{ print $1 }')
+              echo "received key: ${actual_key}"
+              echo "received size: ${size}"
+
+              if [[ "${actual_key}" == "${request_key}" ]]; then
+                touch .task-meta-cache-exact-match
+              fi
+
+              echo "unpacking cache..."
+              tar xzP -f "${cache_file}" || true
+            else
+              echo "no cache loaded"
+            fi
+
+            rm -f "${cache_file}" "${header_file}"
+            end_ts=$(date +%s)
+            echo "loading cache took $(( $end_ts - $start_ts ))s"
+          fi
+  cachesave:
+    cmds:
+      - task: cachesave-root-js
+  cachesave-root:
+    cmds:
+      - task: cachesave-root-js
+  cachesave-root-js:
+    dir: '{{.ROOT_DIR}}'
+    deps:
+      - cachekey-root-js
+    cmds:
+      - cmd: pnpm store path > .task-meta-cache-paths
+      - cmd: |-
+          if [[ -n ${CI_CACHE_TOKEN+x} ]] && [[ -f .task-meta-cache-key ]] && [[ -f .task-meta-cache-paths ]]; then
+            if [[ -f .task-meta-cache-exact-match ]]; then
+              echo "skipping re-upload because an exact match was returned from the cache"
+              exit 0
+            fi
+
+            request_key=$(cat ".task-meta-cache-key")
+            start_ts=$(date +%s)
+            cache_file=$(mktemp)
+
+            echo "packing cache..."
+            tar czP -f "${cache_file}" $(cat .task-meta-cache-paths)
+            size=$(du -h "${cache_file}" | awk '{ print $1 }')
+
+            echo "uploading cache (${size})..."
+            if curl -fsSL -H "authorization: Bearer ${CI_CACHE_TOKEN}" -X PUT "https://ci-cache.markormesher.co.uk/cache/${request_key}" --data-binary "@${cache_file}"; then
+              echo "uploaded cache"
+            else
+              echo "error saving cache"
+            fi
+
+            rm -f "${cache_file}"
+            end_ts=$(date +%s)
+            echo "saving cache took $(( $end_ts - $start_ts ))s"
+          fi
   deps:
     cmds:
-      - task: deps-js-root
-  deps-js:
+      - task: deps-root-js
+  deps-root:
     cmds:
-      - task: deps-js-root
-  deps-js-root:
+      - task: deps-root-js
+  deps-root-js:
     dir: '{{.ROOT_DIR}}'
     cmds:
       - cmd: pnpm install --frozen-lockfile
@@ -167,11 +259,11 @@ tasks:
           cat .task-meta-imgrefs | grep "." || echo "None"
   lint:
     cmds:
-      - task: lint-js-root
-  lint-js:
+      - task: lint-root-js
+  lint-root:
     cmds:
-      - task: lint-js-root
-  lint-js-root:
+      - task: lint-root-js
+  lint-root-js:
     dir: '{{.ROOT_DIR}}'
     cmds:
       - cmd: pnpm lint
